services:
  taskservice:
    build: ./taskservice
    container_name: taskservice
    command: sh -c "python -u -m app.api"
    ports:
      - "5000"
    volumes:
      - ./taskservice:/app
      - ./logs:/app/logs
    networks:
      - internal
    # порты не открываем наружу

  webui:
    build: ./webui
    expose:
      - "5001"
    container_name: webui
    volumes:
      - ./logs:/app/logs
    networks:
      - internal
    restart: unless-stopped

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - taskservice
      - webui
    networks:
      - internal

networks:
  internal:
    driver: bridge