server {
    listen 80;
    server_name localhost;

    # Перенаправление запросов к API
    location /api/ {
        proxy_pass http://taskservice:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Всё остальное — на webui
    location / {
        proxy_pass http://webui:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}